version: '3.9'
services:
  backend:
      build:
        context: ''
        dockerfile: docker/Dockerfile
      container_name: quotes_service
      restart: always
      networks:
        - vpc


networks:
  vpc:
    name: ithappens-bot-network
